name: realworld-hs
version: 0.1.0.0
synopsis: Scotty impl of https://github.com/gothinkster/realworld
license: MIT
author: toptobes

language: GHC2021

ghc-options:
  - -Wall
  - -Wno-orphans
  - -Wno-unrecognised-pragmas
  - -O1

default-extensions:
  - LambdaCase
  - BlockArguments
  - RecordWildCards
  - OverloadedRecordDot
  - OverloadedLabels
  - OverloadedStrings
  - DuplicateRecordFields
  - DeriveAnyClass
  - DerivingStrategies
  - FunctionalDependencies
  - UnicodeSyntax
  - LinearTypes
  - DataKinds
  - TypeFamilies
  - GADTs
  - ViewPatterns

dependencies:
  - name: base
    version: ">=4.16.4.0"
    mixin:
      - hiding (Prelude)
  - name: relude
    version: ">=1.2.0.0"
    mixin:
      - (Relude as Prelude)
      - ""
  - scotty
  - wai-extra
  - mtl
  - unliftio
  - aeson
  - http-types
  - time
  - resource-pool
  - jwt
  - cryptonite
  - memory
  - base64
  - esqueleto
  - persistent
  - persistent-postgresql
  - postgresql-simple
  - file-embed
  - text
  - template-haskell
  - wai-middleware-static

library:
  source-dirs: src
  default-extensions:
    - NoFieldSelectors

executables:
  app:
    main: Main.hs
    source-dirs: app
    dependencies: realworld-hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -O0
    dependencies:
      - hspec
      - realworld-hs
    build-tools: hspec-discover
